# Generated by Django 3.0.4 on 2020-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('FR', 'Fresh news'), ('PO', 'Popular news'), ('HO', 'Hot news')], default='FR', max_length=2),
        ),
    ]
