# Generated by Django 3.0.4 on 2020-05-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200508_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='news tag', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.tag', verbose_name='Tag:'),
        ),
    ]
